# -*- coding: utf-8 -*-
"""Proyecto_final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYiUvugnqXGnpiFoK5LLp9K3-mUTZM2Y
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/Mydrive
!git clone https://github.com/Encryptd404/PROYECTO_FINAL.git

# Commented out IPython magic to ensure Python compatibility.
# %cd PROYECTO_FINAL/
!git checkout Juan_Meneses

import pandas as pd
import numpy as np

Ruta = r"/content/PROYECTO_FINAL/Datos/KL HKL - Spare Part Inventories.csv"
Base_1 = pd.read_csv(Ruta, sep=";")
Base_1.head()

Base_1.info()

Base_1.tail()

print(Base_1.isnull().sum())

Base_1.columns

Base_1.drop(["Model","Specify","Brand","Expiry Age (In Month)"], axis=1, inplace=True)

Base_1.columns

Base_1.shape

print(Base_1.isnull().sum())

Base_1.duplicated()

print(Base_1.duplicated().sum())

Base_1

Base_1.dtypes

Base_1["Min Nos"].head(10)

Base_1["Item Description"].head(30)

Base_1.to_excel('Base_1.xlsx', index=False)

from google.colab import files
files.download('Base_1.xlsx')

"""## Segunda base"""

Ruta_2 = r"/content/PROYECTO_FINAL/Datos/parkinsons_updrs.data.csv"
Base_2 = pd.read_csv(Ruta_2, sep=";")
Base_2.head()

Base_2.info()

Base_2.columns.tolist()

Base_2.columns = Base_2.columns.str.strip()

Base_2["Jitter(Abs)"] = pd.to_numeric(Base_2["Jitter(Abs)"], errors="coerce")

Base_2["Jitter(Abs)"].dtypes
Base_2.head()

print(Base_2.isna().sum())

Base_2.drop(["Jitter(Abs)"], axis = 1, inplace = True)

Base_2.columns

print(Base_2.isnull().sum())

print(Base_2.duplicated())

print(Base_2.duplicated().sum())

Base_2[Base_2['age'] < 0]

Base_2.to_excel('Base_2.xlsx', index=False)

from google.colab import files
files.download('Base_2.xlsx')